wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
architecture:
  desc: null
  value: Vistral-7b-Chat-DPO
dataset:
  desc: null
  value: MISA-WEB-CRAWL
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705485480.858374
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.16.2
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
